name: Test 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release to cut (e.g. 1.2.3)'
        required: false
concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-22.04
    outputs:
      builders: ${{ steps.builders.outputs.builders }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Unit Tests
      run: ./scripts/unit.sh

    - name: Get builders from integration.json
      id: builders
      run: |
        source "${{ github.workspace }}/scripts/.util/builders.sh"
        builders="$(util::builders::list "${{ github.workspace }}/integration.json")"
        echo "builders=${builders}" >> $GITHUB_ENV

  integration:
    name: Integration Tests with Builders
    runs-on: ubuntu-22.04
    needs: unit
    strategy:
      matrix:
        builder: ${{ fromJSON(env.builders) }}
      fail-fast: false
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Checkout
      uses: actions/checkout@v3

    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true

    - name: Run Integration Tests
      run: ./scripts/integration.sh --use-token --builder ${{ matrix.builder }}
      env:
        GIT_TOKEN: ${{ github.token }}
        TMPDIR: "${{ runner.temp }}"

  roundup:
    name: Integration Tests Summary
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    needs: integration
    steps:
    - name: Determine Result
      run: |
        result="${{ needs.integration.result }}"
        if [[ $result == "success" ]]; then
          echo "Integration tests passed against all builders"
          exit 0
        else
          echo "Integration tests failed on one or more builders"
          exit 1
        fi

  upload:
    name: Upload Workflow Event Payload
    runs-on: ubuntu-22.04
    steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: event-payload
        path: ${{ github.event_path }}
